defi-helper/defihelper-backend

- src/queue/pools/swopfiLPFarming.ts
> Unique contract check

- src/queue/pools/masterChief.ts
> Contract unique check

- src/api/router.ts
- src/api/schema/userNotification/index.ts
- src/migrations/M202111261409UserNotification.ts
- src/models/UserNotification/Entity.ts
- src/models/UserNotification/Service.ts
- src/models/UserNotification/index.ts
- src/models/container.ts
- src/models/index.ts
- src/queue/notifications/PortfolioMetrics/broker.ts
- src/services/ACL/container.ts
> User notifications control center

- src/migrations/M202111301759ProtocolContractMetadata.ts
- src/models/Automate/Service.ts
- src/models/Protocol/Entity.ts
- src/models/Protocol/Service.ts
- src/models/container.ts
- src/queue/contract/resolveAbi.ts
- src/queue/index.ts
- src/queue/scanner/registerContract.ts
- src/services/Scanner/index.ts
> Abi resolver

- package-lock.json
- package.json
- src/api/schema/token/index.ts
- src/api/schema/user/index.ts
- src/config/index.ts
- src/container.ts
- src/migrations/M202112031202MetricsStructFixes.ts
- src/models/Metric/Entity.ts
- src/models/Metric/Service.ts
- src/models/Token/Entity.ts
- src/models/Token/Service.ts
- src/queue/index.ts
- src/queue/metrics/moralis/walletBalancesBroker.ts
- src/queue/metrics/moralis/walletBalancesFiller.ts
- src/queue/metrics/utils/index.ts
- src/services/Moralis/index.ts
https://trello.com/c/qYgUCdLv
https://github.com/defi-helper/defihelper-app/pull/118
> Moralis intergrated

- src/locales/enUS.ts
- src/locales/ruRU.ts
- src/queue/index.ts
- src/queue/publicBetaBenefits.ts
- src/queue/publicBetaNotificationAndRunUp.ts
- src/services/Telegram/templates/PublicBetaStarted.mustache
- src/services/Telegram/templates/index.ts
https://trello.com/c/W31NoD3V
https://trello.com/c/jjFSC71S
> Public beta

- src/models/Wallet/Service.ts
- src/queue/events/userCreated.ts
- src/queue/events/walletCreated.ts
- src/queue/index.ts
> Moralis assets on user create 

- src/queue/automate/run.ts
> Disable automate after N retries fix

- src/queue/events/walletCreated.ts
- src/queue/index.ts
- src/queue/wallet/findAppliedNetworks.ts
> Resolve all applied blockchains on wallet address

- src/queue/index.ts
- src/queue/schedule/weekStart.ts
- src/queue/wallet/regularFindUnknownAppliedNetworks.ts
> Regular check wallet networks

- src/queue/wallet/findAppliedNetworks.ts
- src/queue/wallet/regularFindUnknownAppliedNetworks.ts
> Fix null network

- src/api/schema/user/index.ts
- src/queue/wallet/regularFindUnknownAppliedNetworks.ts
https://trello.com/c/VnGIHj5l/
> Tokens by platform

- src/api/router.ts
- src/api/schema/user/index.ts
- src/models/Wallet/Service.ts
- src/queue/events/walletCreated.ts
> On wallet create event

- src/api/schema/user/index.ts
> On wallet create subscription fix

- src/queue/scanner/registerContract.ts
- src/queue/scanner/subscribeToEvent.ts
- src/services/Scanner/index.ts
> Restart task if scanner is in temporary down 

- src/queue/metrics/utils/index.ts
- src/queue/protocol/resolveContracts.ts
- src/services/Blockchain/Adapter.ts
> Adapters api queue postpone on error

- src/queue/billing/emptyWalletsBroker.ts
> Fix queue task

- src/queue/notifications/PortfolioMetrics/sender.ts
This reverts commit 1643e20082414b109746d5ab2b988830dc0dd314.
> Revert "fix"

- src/queue/metrics/walletBalances/walletBalancesDeBankFiller.ts
- src/queue/metrics/walletBalances/walletBalancesMoralisFiller.ts
> zero metrics fix

- src/api/schema/automate/index.ts
- src/automate/condition/ethereumOptimalAutomateRun.ts
- src/migrations/M202202111659ActionNextRestake.ts
- src/models/Automate/Entity.ts
- src/models/Automate/Service.ts
- src/queue/automate/run.ts
> Condition restake date

- src/queue/index.ts
- src/queue/utils/tokensLogoBroker.ts
> Debank icons, merge after types refactor

- src/api/schema/protocol/index.ts
- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
> Debank protocols filter

- src/api/schema/user/index.ts
> tokens on exchange wallet

- src/queue/schedule/hourStart.ts
> debank protocols broker schedule

- src/config/index.ts
- src/queue/metrics/walletBalances/walletBalancesDeBankFiller.ts
- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
- src/queue/schedule/hourStart.ts
- src/queue/token/resolveTokenAliasLiquidity.ts
- src/queue/wallet/findAppliedNetworks.ts
- src/services/Blockchain/Ethereum.ts
> Portfolio tracker improvements

- src/locales/enUS.ts
- src/locales/ruRU.ts
- src/models/Notification/Service.ts
- src/queue/billing/emptyWalletsBroker.ts
- src/queue/notifications/AutomateWalletsNotEnoughFunds/sender.ts
- src/services/Email/templates/ConfirmEmail.mustache
> Confirm email fix

- src/queue/protocol/resolveContracts.ts
- src/queue/scanner/registerContract.ts
> Recreate events listeners

- src/api/router.ts
- src/api/schema/landing/index.ts
> Medium posts 

- src/queue/metrics/walletBalances/walletBalancesBroker.ts
https://trello.com/c/b2irxxRN
нашел только 1 место
> Deleted at fix

- src/models/Protocol/Service.ts
- src/server.ts
> skip emit event for contract wallet link with duplicate

- src/api/cli/billing.ts
- src/migrations/M202106211057Queue.ts
- src/migrations/M202208011419QueueExecutionTime.ts
- src/models/Queue/Entity.ts
- src/models/Queue/Service.ts
- src/models/Token/Service.ts
- src/queue/billing/broker.ts
- src/queue/events/contractBlockchainCreated.ts
- src/queue/system/garbageCollector.ts
> add queue task execution time and remove collision sign

- src/queue/events/walletContractLinked.ts
> remove get contract without blockchain in event wallet-contract link

- src/models/Notification/Service.ts
- src/queue/index.ts
- src/queue/notifications/AutomateWalletsNotEnoughFunds/sender.ts
- src/queue/notifications/PortfolioMetrics/sender.ts
- src/queue/notifications/send.ts
- src/queue/telegram/sendByContact.ts
- src/services/Cache/index.ts
> deactivate blocked tg contacts

- src/api/router.ts
> protocol apy preview fixed

- src/migrations/M202208091420ProtocolsAdapterIndex.ts
> adapter index

- src/locales/enUS.ts
- src/locales/ruRU.ts
- src/queue/notifications/PortfolioMetrics/sender.ts
- src/services/Email/templates/PortfolioMetrics.mustache
- src/services/Telegram/templates/PortfolioMetrics.mustache
> Portfolio tracked percentage change

- src/queue/billing/claimScan.ts
- src/queue/billing/storeScan.ts
- src/queue/billing/transferScan.ts
> Notify only blocks lag

- package-lock.json
- package.json
- src/automate/action/ethereumAutomateRun.ts
- src/config/index.ts
- src/container.ts
- src/queue/metrics/walletBalances/walletBalancesWavesFiller.ts
- src/services/Amplitude/index.ts
> amplitude server side events

- src/api/schema/store/index.ts
- src/migrations/M202208181100FreeStoreProduct.ts
- src/queue/events/userCreated.ts
> 50 free notifications

- src/queue/events/walletCreated.ts
> waves wallets filler

- src/queue/index.ts
- src/queue/log/stuckQueueTaskWarning.ts
- src/queue/schedule/hourStart.ts
https://trello.com/c/H1tbE7J3
https://trello.com/c/PHTwYuqF
(одна задача, обсуждали)
> Stucked tasks notify

- src/api/schema/billing/index.ts
- src/migrations/M202208151200BillingTransferStatus.ts
- src/models/Billing/Entity.ts
- src/models/Billing/Service.ts
- src/queue/billing/transferScan.ts
- src/queue/events/billing/transferTxCreated.ts
- src/queue/index.ts
> billing status and confirmation transfer after created

- src/queue/notifications/migratablePoolsBroker.ts
- src/queue/notifications/migratablePoolsNotifyUser.ts
- src/services/Telegram/templates/AutomationsMigrableContracts.mustache
> Migratable pools notifications improvements

- src/queue/billing/feeOracle.ts
> bills limit 1 for fee oracle task

- src/telegram.ts
> telegram bot create user

- src/migrations/M202209081007UserMetricsTracking.ts
- src/models/User/Entity.ts
- src/models/User/Service.ts
- src/queue/index.ts
- src/queue/metrics/userMetricsTrackingConditionsBroker.ts
- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankBroker.ts
- src/queue/schedule/dayStart.ts
> Debank protocols - collect conditions

- src/api/schema/user/index.ts
> locale mutation

- src/api/schema/user/index.ts
> portfolio freezed at

- src/queue/metrics/userMetricsTrackingConditionsBroker.ts
> metrics tracking conditions

- src/telegram.ts
> welcome template fix

- src/queue/index.ts
- src/queue/log/garbageCollector.ts
- src/queue/metrics/garbageCollector.ts
- src/queue/schedule/dayStart.ts
> metrics and log garbage collector

- src/api/schema/user/index.ts
- src/queue/metrics/userMetricsTrackingConditionsBroker.ts
> fix contract where

- src/migrations/M202209221612LogTimestampsIndex.ts
> log createdAt index

- src/api/router.ts
> opengraph image fix apy

- src/api/dataLoader/protocol/index.ts
- src/api/dataLoader/token/index.ts
- src/api/dataLoader/user/index.ts
- src/api/schema/protocol/index.ts
- src/api/schema/token/index.ts
- src/api/schema/types.ts
- src/api/schema/user/index.ts
- src/models/Metric/Service.ts
> remove week and month metrics change

- src/container.ts
- src/services/Numbers/index.ts
- src/services/Telegram/templates/PortfolioMetrics.mustache
- src/services/Template/container.ts
> numbers formatter

- src/api/schema/protocol/index.ts
> protocols tvl sort

- src/api/schema/automate/index.ts
- src/models/Automate/Entity.ts
- src/models/Automate/Service.ts
- src/queue/events/automate/contractStopLossEnabled.ts
> stop loss with in token

- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/Entity.ts
- src/models/SmartTrade/handlers/swap.ts
> Smarttrade tralling

- src/api/router.ts
- src/api/schema/smartTrade/index.ts
- src/services/ACL/container.ts
> mutation for cancel smart trade order

- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
- src/services/Debank/index.ts
> fix debank request error catching

- src/api/schema/user/index.ts
- src/models/Metric/Service.ts
- src/models/Protocol/Service.ts
- src/models/Wallet/Service.ts
- src/queue/metrics/contractAprWeekRealBroker.ts
- src/queue/metrics/contractBroker.ts
- src/queue/metrics/walletBalances/cex/walletBalancesUniversalFiller.ts
- src/queue/metrics/walletBalances/walletBalancesDeBankFiller.ts
- src/queue/metrics/walletBalances/walletBalancesWavesFiller.ts
- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
- src/queue/metrics/walletBroker.ts
> remove promise all queries for metrics brokers

- src/api/schema/protocol/index.ts
- src/container.ts
- src/migrations/M202210031057TokenCoingeckoId.ts
- src/models/Token/Entity.ts
- src/models/Token/Service.ts
- src/queue/index.ts
- src/queue/token/syncCoingeckoIdsBroker.ts
- src/queue/token/syncCoingeckoIdsFiller.ts
- src/services/Blockchain/Ethereum.ts
- src/services/Coingecko/index.ts
> coingecko ids pairing

- src/queue/index.ts
- src/queue/notifications/demoCallInvitationsBroker.ts
- src/services/Telegram/templates/DemoCallInvite.mustache
- src/services/Telegram/templates/index.ts
> telegram invite call

- src/api/router.ts
- src/api/schema/restakeStrategy/index.ts
> restake calculator

- src/api/schema/protocol/index.ts
> debank contracts list fix

- src/api/router.ts
- src/api/schema/notification/index.ts
- src/models/Notification/Service.ts
> api subscripe for user contact activated event

- src/api/schema/config/index.ts
> filter blockchain list on config with autorestake flag

- src/api/schema/billing/index.ts
- src/api/schema/types.ts
- src/migrations/M202210131649BillingTransferDoublePrecision.ts
- src/migrations/M202210131651BillingBillDoublePrecision.ts
- src/migrations/M202210131721BillingAmountClear.ts
- src/models/Billing/Entity.ts
- src/models/Billing/Service.ts
- src/queue/billing/claimScan.ts
- src/queue/billing/transferScan.ts
- src/queue/events/billing/transferTxCreated.ts
> Billing double float

- src/api/schema/billing/index.ts
> wallet low fee founds with unconfirmed transfer

- src/api/schema/automate/index.ts
- src/server.ts
> remove trigger with autorestake contract

- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
> debank staking clear fix

- src/api/router.ts
- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/Entity.ts
- src/services/ACL/container.ts
> update smart trade order

- src/api/dataLoader/container.ts
- src/api/dataLoader/user/index.ts
- src/api/schema/user/index.ts
- src/migrations/M202210181714AutomateContractWallet.ts
- src/migrations/M202210181741AutomateContractWalletFiller.ts
- src/models/Automate/Entity.ts
- src/models/Automate/Service.ts
- src/queue/events/automate/contractVerificationConfirmed.ts
> wallet automates list

- src/api/dataLoader/automate/index.ts
- src/api/dataLoader/container.ts
- src/api/router.ts
- src/api/schema/automate/index.ts
- src/migrations/M202210201830AutomateInvestHistory.ts
- src/models/Automate/Entity.ts
- src/models/Automate/Service.ts
- src/models/container.ts
- src/services/ACL/container.ts
> automate invest history

- src/api/dataLoader/token/index.ts
- src/api/schema/token/index.ts
- src/queue/metrics/tokenRiskRankingFiller.ts
- src/services/RiskRanking/index.ts
> quantile risk rates

- src/api/router.ts
- src/api/schema/billing/index.ts
> zap billing log

- src/automate/action/ethereumAutomateRun.ts
- src/queue/automate/notifyExecutedRestake.ts
- src/queue/index.ts
- src/services/Telegram/templates/AutomateRestakeDone.mustache
- src/services/Telegram/templates/index.ts
> tg notify on restake

- src/api/router.ts
- src/api/schema/monitoring/index.ts
> monitoring telegram

- src/api/router.ts
- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/Service.ts
> smart trade order upgraded subscribe

- package-lock.json
- package.json
- src/api/router.ts
- src/api/schema/smartTrade/index.ts
- src/migrations/M202211031622SmartTradeOrderClaim.ts
- src/models/SmartTrade/Entity.ts
- src/models/SmartTrade/Service.ts
- src/models/SmartTrade/handlers/swap.ts
- src/queue/smartTrade/orderStatusResolve.ts
- src/services/ACL/container.ts
> smart trade order claim

- src/migrations/M202211090955ResetMetricsTracking.ts
- src/models/Notification/Service.ts
- src/queue/events/notifications/contactActivated.ts
- src/queue/index.ts
- src/queue/metrics/userBroker.ts
- src/queue/metrics/userPortfolioFiller.ts
> metrics tracked fix

- src/api/schema/smartTrade/index.ts
- src/migrations/M202211091148SmartTradeOrderBalances.ts
- src/models/SmartTrade/Entity.ts
- src/models/SmartTrade/Service.ts
- src/models/Token/Service.ts
- src/queue/events/smartTrade/orderConfirmed.ts
- src/queue/index.ts
- src/queue/smartTrade/orderBalancesFiller.ts
- src/queue/smartTrade/orderStatusResolve.ts
> smart trade order balances

- src/queue/index.ts
- src/queue/metrics/notifyLostMetricChains.ts
- src/queue/notifications/migratablePoolsNotifyUser.ts
> notify stucked metrics 

- src/api/schema/token/index.ts
> find tokens alias by symbol list

- src/api/schema/smartTrade/index.ts
> sort smart trade order by updated at

- src/api/schema/smartTrade/index.ts
> filter by claim for smart trade order list

- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/Entity.ts
- src/queue/smartTrade/orderBalancesFiller.ts
> smart trade order swap price

- src/api/router.ts
> context for subscribtions

- src/queue/schedule/dayStart.ts
> schedule metricsNotifyLostChain

- src/services/Telegram/templates/AutomationsMigrableContracts.mustache
> migratable pools notification text fix

- src/api/schema/protocol/index.ts
> contract list filter with tags

- src/api/dataLoader/protocol/index.ts
- src/api/schema/automate/index.ts
- src/api/schema/protocol/index.ts
- src/migrations/M202211301614RemoveBlockchainContractMetricField.ts
- src/migrations/M202211301616RemoveDebabkContractMetricField.ts
- src/models/Protocol/Entity.ts
- src/models/Protocol/Service.ts
- src/queue/contract/riskCalculationFiller.ts
- src/queue/metrics/contractAprWeekReal.ts
- src/queue/metrics/utils/index.ts
- src/queue/metrics/walletBalances/walletProtocolsBalancesDeBankFiller.ts
- src/queue/notifications/migratablePoolsNotifyUser.ts
- src/queue/protocol/resolveContracts.ts
> remove contract metric field

- src/queue/notifications/AutomateWalletsNotEnoughFunds/sender.ts
> low fee funds fix

- src/queue/events/smartTrade/orderConfirmed.ts
- src/queue/index.ts
- src/queue/notifications/smartTrade/orderCreated.ts
- src/queue/notifications/smartTrade/orderSucceeded.ts
- src/services/Telegram/templates/SmartTradeOrderCreated.mustache
- src/services/Telegram/templates/SmartTradeOrderSucceeded.mustache
- src/services/Telegram/templates/index.ts
> smart trade order change status notifications

- src/api/dataLoader/protocol/index.ts
- src/api/dataLoader/token/index.ts
- src/api/dataLoader/user/index.ts
- src/api/schema/user/index.ts
> get latest registry metrics with date below

- src/api/dataLoader/protocol/index.ts
> remove hidden and deprecated contracts from protocol metrics

- src/api/schema/billing/index.ts
> active automates count fix

- src/api/schema/tag/index.ts
- src/migrations/M202212081220TagPosition.ts
- src/models/Tag/Entity.ts
- src/models/Tag/Service.ts
> tag position

- src/api/dataLoader/token/index.ts
- src/queue/metrics/poolRiskRankingFiller.ts
- src/queue/schedule/dayStart.ts
- src/services/RiskRanking/index.ts
> protocol risk ranking

- src/api/schema/user/index.ts
> add is metrics tracked flag in user api

- src/queue/index.ts
- src/queue/metrics/lostMetricFiller.ts
- src/queue/schedule/dayStart.ts
> lost metrics filler

- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/handlers/swap.ts
> take profit moving

- src/queue/metrics/poolRiskRankingBroker.ts
- src/queue/metrics/poolRiskRankingFiller.ts
> use token parts for pool risk filler

- src/api/cli/billing.ts
- src/queue/billing/broker.ts
> balance contract in billing broker fix

- src/api/schema/smartTrade/index.ts
- src/models/SmartTrade/Entity.ts
- src/models/SmartTrade/handlers/swap.ts
- src/queue/index.ts
- src/queue/smartTrade/orderTimeout.ts
> Smarttrade timeout

- src/queue/metrics/notifyLostMetricChains.ts
- src/queue/schedule/dayStart.ts
> call last metrics filler task after notify lost chains

- src/queue/metrics/walletBalances/walletBalancesDeBankFiller.ts
- src/services/Debank/index.ts
> debank balance filler later attempt

- src/api/router.ts
- src/services/Email/templates/AutomateNotEnoughFunds.mustache
- src/services/Email/templates/ConfirmEmail.mustache
- src/services/Email/templates/PortfolioMetrics.mustache
> use url instead attachment

- src/api/schema/user/index.ts
> wallet tokens list fix

- src/models/Notification/Entity.ts
- src/models/Notification/Service.ts
- src/models/Store/Service.ts
- src/queue/events/notifications/notificationCreated.ts
- src/queue/notifications/PortfolioMetrics/hourly.ts
- src/queue/notifications/PortfolioMetrics/sender.ts
- src/services/Email/templates/NotificationsFew.mustache
- src/services/Email/templates/NotificationsOver.mustache
- src/services/Email/templates/index.ts
- src/services/Telegram/templates/NotificationsFew.mustache
- src/services/Telegram/templates/NotificationsOver.mustache
- src/services/Telegram/templates/index.ts
> portfolio metrics notify with store

- src/api/dataLoader/container.ts
- src/api/dataLoader/token/index.ts
- src/api/schema/protocol/index.ts
> contract tokens with data loader

- src/api/schema/user/index.ts
> wallet metrics scan mutation without contract link

- src/queue/automate/contractEthereumVerify.ts
> automate contract verification reject error length fix

- src/api/schema/protocol/index.ts
> api contracts list search fix

- src/container.ts
- src/queue/scanner/registerContract.ts
- src/services/Scanner/index.ts
> watcher history sync

- src/models/Metric/Service.ts
- src/models/Notification/Entity.ts
- src/queue/events/metrics/metricUni3WalletCreated.ts
- src/queue/index.ts
- src/queue/metrics/utils/index.ts
- src/services/Telegram/templates/Uni3PositionWithoutReward.mustache
- src/services/Telegram/templates/index.ts
> notify user if exists automates without rewards

- src/migrations/M202301271314Uni3ProtocolWatcher.ts
- src/queue/scanner/registerContract.ts
> register contract in watcher with 6 months ago history scan

- src/queue/automate/contractStopLossTx.ts
> scan metrics after stop loss completed

- src/queue/token/uniswapRouteRevealer.ts
> fix auto price feed resolver with zero price

- src/automate/action/ethereumAutomateRun.ts
- src/queue/automate/notifyExecutedRestake.ts
- src/services/Telegram/templates/AutomateRestakeDone.mustache
> autorestake notificaionts more info

- src/automate/condition/ethereumOptimalAutomateRun.ts
> autorestake optimal condition earned fix

- src/automate/condition/ethereumOptimalAutomateRun.ts
> add 1 usd to autorestake optimal calculate

- src/api/dataLoader/automate/index.ts
- src/api/router.ts
- src/api/schema/automate/index.ts
- src/migrations/M202301311610AutomateInvestHistoryTx.ts
- src/models/Automate/Entity.ts
- src/models/Automate/Service.ts
- src/queue/automate/investHistoryTx.ts
- src/queue/index.ts
> wait tx for automate invest history

- src/api/dataLoader/container.ts
- src/api/dataLoader/user/index.ts
- src/api/schema/automate/index.ts
- src/queue/events/metrics/metricUni3WalletCreated.ts
> uni3 metrics in price range flag

- src/queue/metrics/contractAprWeekReal.ts
> remove zero token price from real apy calculate

- src/queue/events/metrics/metricUni3WalletCreated.ts
- src/services/Telegram/templates/Uni3PositionWithoutReward.mustache
> uni3 out of range notification fix

- src/api/schema/automate/index.ts
> automate metrics balance

- src/queue/automate/uni3RebalanceTx.ts
- src/queue/events/metrics/metricUni3WalletCreated.ts
- src/queue/index.ts
- src/queue/metrics/utils/index.ts
- src/queue/notifications/uniswap3/rebalance.ts
- src/services/Cache/index.ts
- src/services/Telegram/templates/Uni3PositionRebalance.mustache
- src/services/Telegram/templates/index.ts
> uni3 rebalance notification

- src/queue/events/metrics/metricUni3WalletCreated.ts
> uni3 rebalance throttle

- src/services/Blockchain/Ethereum.ts
> fix optimistic native token name

- src/api/schema/automate/index.ts
- src/queue/events/metrics/metricUni3WalletCreated.ts
> uni3 automate token id

- src/api/schema/automate/index.ts
> uni3 out of range fix

- src/api/dataLoader/automate/index.ts
- src/api/dataLoader/container.ts
- src/api/schema/automate/index.ts
> uni3 rebalance api

- src/queue/automate/contractStopLossTx.ts
> refund invest after invest

- src/api/dataLoader/user/index.ts
- src/api/schema/automate/index.ts
- src/queue/index.ts
- src/queue/metrics/automateFeeApy.ts
- src/queue/metrics/automateFeeApyBroker.ts
- src/queue/metrics/utils/index.ts
- src/queue/schedule/dayStart.ts
> fee day apr
